version: '3.7'

services:
  app:
    image: python:3.12-slim
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    environment:
      - PIP_ROOT_USER_ACTION=ignore
    ports:
      - "8000:8000"
